org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false

mod_name=VS Marine Propulsion
mod_id=vs_marine_propulsion
mod_version=0.0.1-alpha
mod_description=Exploring options for Valkyrien Skies watercraft propulsion.
mod_license=CC BY-SA
mod_author=Daniel366Cobra
homepage=https://github.com/Daniel366Cobra/VS-Marine-Propulsion-Forge
sources=https://github.com/Daniel366Cobra/VS-Marine-Propulsion-Forge
issue_tracker=https://github.com/Daniel366Cobra/VS-Marine-Propulsion-Forge/issues

archives_base_name=vs_marine_propulsion
maven_group = io.github.daniel366cobra

minecraft_version=1.20.1
forge_version=47.2.0
mapping_channel=official
mapping_version=1.20.1

vs2_version=2.1.4+be944c11b4
vs_core_version=1.1.0+8a93383ce5
block_external_repositories=
